### ISSUE TITLE
Example UFO generation script does not work

### ISSUE THREAD

**Issue by moyogo** [spiratype/vfb_ufo3#1]
After copying the .py and .pyd file to Lib/site-packages/vfb_ufo3, running the example UFO generation script fails with the following error:
```
Traceback (most recent call last):
  File "<string>", ine 41, in <module>
TypeError: write_ufo() got an unexpected keyword argument 'decompose_glyphs'
```
The same error occurs with `remove_glyph` when `decompose_glyphs` is commented out in https://github.com/spiratype/vfb_ufo3/blob/master/__init__.py#L100.

**Comment by spiratype** [comment]
I have corrected the sample script. The arguments had been changed as more features were added and I failed to update the sample script.
