### ISSUE TITLE
Please add install instructions

### ISSUE THREAD

**Issue by felipesanches** [spiratype/vfb_ufo3#2]
I tried installing this from pypi into a python 3 virtual environment and it said python 2.7 is required.

![Screenshot from 2019-11-09 09-13-32](https://user-images.githubusercontent.com/213676/68528432-6b4f4900-02d1-11ea-989b-ccef9bcb819f.png)

Then I tried again in a python 2.7.16 virtualenv and it seems to be picky about needing `python_version==2.7`:

![Screenshot from 2019-11-09 09-14-48](https://user-images.githubusercontent.com/213676/68528439-7b672880-02d1-11ea-8269-f88205a423b1.png)

**Comment by spiratype** [comment]
This is for Windows FontLab 5.2, which only works with 32-bit Python 2.7.
