### ISSUE TITLE
Does it depend on FontLab?

### ISSUE THREAD

**Issue by felipesanches** [spiratype/vfb_ufo3#3]
I noticed that on `src/core.pyx` there's this:

```python
from FL import fl, Font, Rect
import FL
```

And I also could not easily find in the source code any actual parsing of the binary file format.
Does it mean the parsing is done by the FontLab proprietary code? If so, then it turns out that this project is not really what I am looking for.

**Comment by spiratype** [comment]
Very much so. The .vfb file format is proprietary and all work is done from within FontLab itself.
